name: Code Quality Checks
on: [pull_request]

permissions:
  pull-requests: write
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '^8.6.6'
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Lint with TypeScript
        uses: EPMatt/reviewdog-action-tsc@v1
        with:
          reporter: github-pr-review
          filter_mode: nofilter
      - name: Lint with ESLint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          filter_mode: nofilter
      - uses: EPMatt/reviewdog-action-prettier@v1
        with:
          reporter: github-pr-check
