name: PR-Check
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: '^8.6.2'
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'
      - run: pnpm install
      - uses: EPMatt/reviewdog-action-tsc@v1
        with:
          reporter: github-pr-check
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-check
      - uses: EPMatt/reviewdog-action-prettier@v1
        with:
          reporter: github-pr-check
